// Auto-generated by Portfolio Generator SaaS
// Edit this file to customise your portfolio data

export interface NavItem { label: string; targetId: string; }
export interface ExpertiseItem {
  id: string; num: string; name: string; desc: string;
  type: "dna" | "neural" | "mandala" | "network" | "atom" | "spectrum";
}
export interface ProjectItem {
  id: string; num: string; cat: string; flip: boolean;
  titlePrefix: string; titleHighlight: string; titleSuffix?: string;
  img: string; desc: string; tech: string[]; link: string;
}
export interface TrainingItem { title: string; org: string; desc: string; active: boolean; }
export interface HackathonItem { name: string; date: string; desc: string; }
export interface StatItem { n: string; l: string; }
export interface SocialLink { label: string; url: string; isDownload?: boolean; }
export interface CustomSectionItem { id: string; heading: string; subheading?: string; body?: string; icon?: string; url?: string; }
export interface CustomSection { id: string; type: string; title: string; visible: boolean; items: CustomSectionItem[]; }

export const portfolioData = {
  backgroundAnimation: "vortex",
  colorPalette: "cyber-blue",
  customAccentColor: "",
  personal: {
  "name": "layla said",
  "firstName": "LAYLA",
  "lastName": "SAID",
  "logoText": "LS",
  "role": "Full-Stack Developer",
  "availabilityText": "Open to Work",
  "tagline": "Portfolio — 2025 / 2026",
  "education": "Your University",
  "heroDescription": "Crafting intelligent, scalable digital systems.",
  "heroSubTextLine1": "Full-Stack Developer crafting",
  "heroSubTextLine2": "intelligent, scalable digital systems.",
  "primaryCtaText": "View Work",
  "secondaryCtaText": "Let's Talk",
  "scrollText": "Scroll",
  "email": "your@email.com",
  "photoUrl": "",
  "photoPosition": "right",
  "cvUrl": ""
},

  seo: {
  "title": "layla said — Portfolio",
  "description": "Portfolio of layla said — ",
  "ogTitle": "layla said — Portfolio",
  "ogDescription": "Full-Stack Developer portfolio"
},

  navigation: [
    { label: "Expertise", targetId: "tiles" },
    { label: "Work", targetId: "projects" },
    { label: "About", targetId: "about" },
    { label: "Timeline", targetId: "experience" },
    ...[],
    { label: "Contact", targetId: "contact" },
  ] as NavItem[],

  marquee: ["react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react","react"],

  expertiseHeader: {
  "titleMain": "Core",
  "titleAccent": "Expertise",
  "badge": "06 Domains"
},

  expertise: [
  {
    "id": "tile-1",
    "num": "01",
    "name": "Frontend",
    "desc": "React, TypeScript, modern UI",
    "type": "atom"
  },
  {
    "id": "tile-2",
    "num": "02",
    "name": "Backend",
    "desc": "Node.js, APIs, databases",
    "type": "neural"
  }
] as ExpertiseItem[],

  projectsHeader: {
  "titleMain": "Deployed",
  "titleAccent": "Systems"
},

  projects: [] as ProjectItem[],

  about: {
    ...{
  "statementLine1": "Building the",
  "statementHighlight": "intelligent",
  "statementLine2": "web, one",
  "statementLine3": "system at a time.",
  "paragraphs": []
},
    stats: [
  {
    "n": "5+",
    "l": "Projects"
  }
] as StatItem[],
  },

  timeline: {
    ...{
  "titleMain": "Track",
  "titleAccent": "Record",
  "trainingColumnTitle": "Training & Certifications",
  "hackathonsColumnTitle": "Hackathons"
},
    training: [] as TrainingItem[],
    hackathons: [] as HackathonItem[],
  },

  contact: {
    ...{
  "label": "— Get in touch",
  "headingLine1": "Let's",
  "headingHighlight": "Build",
  "headingLine2": "Together",
  "email": "your@email.com",
  "emailSubject": "Let's connect"
},
    socials: [] as SocialLink[],
  },

  footer: {
  "author": "layla said",
  "logo": "LS.",
  "credit": "Designed & Built by layla said"
},

  customSections: [] as CustomSection[],
};
